config/routes.rb
RailsSkeleton::Application.routes.draw do

  resources :teams do
    resources :messages
    resources :members
  end

  resources :messages
  resources :password_resets
  resources :user_activations
  resources :user_sessions
  resources :users

  root :to => "teams#index"

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :team_user

  delegate :user, :to => :team_user
  delegate :team, :to => :team_user

  validates :user, presence: true, associated: true

  scope :newest_first, -> { order("created_at DESC") }
  scope :current_team, -> team_id { select("DISTINCT ON (user_id) *").where(:team_id => team_id).order("user_id, created_at DESC") }

  after_commit :signal_redis_queue

  protected

  def signal_redis_queue
    $redis.rpush "teamlog:team-alert", team_user.team_id
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :check_logged_in!

  def index
    @messages = Message.order("created_at DESC").all.to_a
  end

  def new
    @message = Message.new
    @message.user = current_user
    @message.team = team
  end

  def create
    @message = Message.new(message_params)
    @message.team_user = TeamUser.where(:user_id => current_user.id, :team_id => team.id).first

    if @message.save
      redirect_to team_path(team)
    else
      render "new"
    end
  end

  private

  def team
    @team ||= current_user.teams.find(params[:team_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_list.html.haml
%table.table

  %thead
    %tr
      %th Date
      %th User
      %th Content

  %tbody
    - messages.each do |message|
      %tr
        %td= l message.created_at
        %td= message.user.email
        %td= message.content

app/views/messages/index.html.haml
%h1 messages index

%p= link_to "create a new message", new_message_path

%table.table

  %thead
    %tr
      %th Date
      %th User
      %th Content

  %tbody
    - @messages.each do |message|
      %tr
        %td= l message.created_at
        %td= message.user.email
        %td= message.content

%p= link_to "create a new message", new_message_path

app/views/messages/new.html.haml
.form-container

  %h1 Update your status

  = simple_form_for [ @message.team, @message ] do |f|

    = f.input :content, :autofocus => "autofocus"

    = f.submit