config/routes.rb
RailsSkeleton::Application.routes.draw do

  resources :teams do
    resources :messages
    resources :members
  end

  resources :messages
  resources :password_resets
  resources :user_activations
  resources :user_sessions
  resources :users

  root :to => "teams#index"

end

app/models/user_session.rb
class UserSession

  include ActsLikeActiveRecord

  attr_reader :user, :email, :password

  def save
    @user ||= User.where("LOWER(email) = ?", email.to_s.strip.downcase).first
    @user && @user.password == password
  end

  def self.create(attributes = {})
    user_session = UserSession.new(attributes)
    user_session if user_session.authorized?
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)

    if @user_session.save
      self.current_user = @user_session.user
      flash[:notice] = "you are now signed in"
      redirect_to root_path
    else
      flash.now[:error] = "couldn't sign in"
      render :action => :new
    end
  end

  def destroy
    self.current_user = nil
    redirect_to new_user_session_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password)
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.haml
.form-container

  %h1 Sign In

  = simple_form_for @user_session do |f|

    = f.input :email, :required => false
    = f.input :password, :required => false

    = f.submit

  %p
    perhaps you'd like to
    = link_to "create a user", new_user_path
    instead?
  %p
    or you need to
    = link_to "reset your password", new_password_reset_path