config/routes.rb
RailsSkeleton::Application.routes.draw do

  resources :teams do
    resources :messages
    resources :members
  end

  resources :messages
  resources :password_resets
  resources :user_activations
  resources :user_sessions
  resources :users

  root :to => "teams#index"

end

app/views/layouts/application.html.haml
!!!
%html

  %head

    %title Rails Skeleton 3.2

    = stylesheet_link_tag :application, media: "all"
    <script type="text/javascript" src="//use.typekit.net/zhv5xth.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    = csrf_meta_tags

  %body

    .top-line
      .top-line-left
        %span.brand
          <span class="brand-first">Status</span><span class="brand-second">Keeper</span>
      .top-line-right
        .line1
          - if current_user && current_user.teams.count > 1
            = link_to "teams", teams_path
            &bull;
          - if current_user
            = current_user.email
            &bull;
            = link_to "sign out", user_session_path(current_user), :method => :delete
        - if @team
          .line2
            %span.team
              = link_to @team.name, team_path(@team)
            &bull;
            = link_to "add member", new_team_member_path(@team)
            /&bull;
            /= link_to "update your status", new_team_message_path(@team)

    - if flash[:error].present?
      .alert.alert-error= flash[:error]
    - if flash[:notice].present?
      .alert.alert-notice= flash[:notice]

    .main-content
      = yield

    = javascript_include_tag :application
    = onload_tag